### ISSUE TITLE
add lib 

### ISSUE THREAD

**Issue by Xaego** [dylanhogg/awesome-python#25]
Visually explore Python object graphs
https://github.com/mgedmin/objgraph

**Comment by dylanhogg** [comment]
Cheers. I'll add these and some of your other suggestions in the next release soon.

**Comment by Xaego** [comment]
Serverless Streamlit
[stlite](https://github.com/whitphx/stlite)

**Comment by Xaego** [comment]
https://github.com/KimiNewt/pyshark
Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
[Fake2DB](https://github.com/emirozer/fake2db)
create custom test databases that are populated with fake data

**Comment by Xaego** [comment]
Python framework for building microservices
https://github.com/nameko/nameko

**Comment by dylanhogg** [comment]
Thanks for your suggestions, these have been added to the core awesome python list.

Due to some quality checks, not all are included in the README or the default view of the website. As the repos collect more stars (or stars per week) they will appear in both these places.

The full, unfiltered list can be seen here: https://www.awesomepython.org/?full=1
